### ISSUE TITLE
Add time stamp in notification email

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [abizerlokhandwala/Cowin-Notification-Service#19]
> 
> New vaccine slot available!
> Apollo Hospital in Cochin on 05-06-2021 **@ 1641 IST**
> 

This would let the user know that , appointments open at this time. #11

**Comment by abizerlokhandwala** [comment]
Hey!
As we are sending real-time notifications, the appointments open at the time you get the notification. Though, these are not consistent throughout different days in most cases.
