### ISSUE TITLE
Slots array is empty

### ISSUE THREAD

**Issue by Saunved** [abizerlokhandwala/Cowin-Notification-Service#7]
![slots_missing_issue](https://user-images.githubusercontent.com/16450673/117696855-68435a80-b1df-11eb-9e72-59497297bfa4.png)
The slots array in this email is blank. Is this a bug or the data isn't available? Just reporting in case this is a bug!

**Comment by abizerlokhandwala** [comment]
Slot timings for other centers are valid, I believe the Cowin API missed out on the slot data here.
